#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 31 16:23:48 2018

@author: Nicholas
"""


class entry:    # creates object for each entry
    
    def __init__(self,num, loc):
        self.num = num
        self.loc = loc

        
    def getNum(self):
        return str(self.num)
    
    def getLoc(self):
        return self.loc.rstrip()
    
    
def main():
    infile = open('Z99_t1h_snps.txt', 'r')   # read in csv generated by SEattempt
    out = open('Z99_t1h_bed.txt', 'w')
    

    for line in infile:
        reads = line.split(':')
        field = entry(reads[0], reads[1])
        chr_num = field.getNum()
        chr_loc = int(field.getLoc())
        chr_end = chr_loc + 1
        snp = "chr"+str(chr_num) +":"+ str(chr_loc) +"-"+ str(chr_end)
        out.write(snp+"\n")
        
        

    
    


    
    
# outputs findings as chr#:snp locus        
    infile.close
    out.close
    
    
        
main()